### ISSUE TITLE
[Question] How do I authenticate my private registry?

### ISSUE THREAD

**Issue by dathdev** [necccc/npm-migrate#8]
I've been trying to use this script to migrate my npm packages from Azure to Nexus but both of them has authentication on them so it keeps giving me 401. Can I still use this script to migrate or do I need to think of some other way around? Thanks.

**Comment by BBlackwo** [comment]
@dathdev You just need to have access to read/publish to each private registry and then the script will work. When you authenticate, the credentials should be written to your `.npmrc`. Then this, or any script should work.

**Comment by dathdev** [comment]
@BBlackwo I can `npm install` a package from the source repo, but the script still fails with 401.

Edit: Added `always-auth=true` into .npmrc, worked perfectly. Thanks!
